create PR to show ERR message
jonatsuji/capstone-project pull request #10
Opened 2023-01-18 10:36 UTC by jonatsuji

2023-01-18 11:58 UTC, ThomasKirst requested changes
Found two little issues in you comments API route.

2023-01-18 11:58 UTC, ThomasKirst commented on pages/api/comments/[id].js
> +    }
`else` missing? ;)

2023-01-18 11:58 UTC, ThomasKirst commented on pages/api/comments/[id].js
> +    }
`else` missing?

2023-01-18 15:36 UTC, jonatsuji commented
to be reviewed: Comments.js / api-pages of both collections / db-Folder

2023-01-18 16:00 UTC, ufelgen reviewed
hab dir ein paar Kommentare da gelassen :) coole Datenbank!

2023-01-18 16:00 UTC, ufelgen commented on components/SinglePageComponents/Comments.js
> +      });
```suggestion
      const routeComments = data.filter((comment) => {
          return comment.routeID === currentRouteID
        }
      });
```

ich glaub das geht auch so

2023-01-18 16:00 UTC, ufelgen commented on components/SinglePageComponents/Comments.js
> +    const newRating = rating;
kommt das nicht aus dem Formular?

2023-01-18 16:00 UTC, ufelgen commented on components/SinglePageComponents/Comments.js
> +  console.log(comments, "FOR ID");
bitte löschen

2023-01-18 16:00 UTC, ufelgen commented on components/SinglePageComponents/Comments.js
> +    const newRating = rating;
habs gefunden :)

2023-01-18 16:00 UTC, ufelgen commented on db/Models/Comments.js
> +  routeID: { type: String, required: true },
wäre es hier nicht eine commentID?

2023-01-18 16:00 UTC, ufelgen commented on pages/api/comments/[id].js
> +// /api/questions/6390625d81028414270e1657 // [id]
kannst du löschen

2023-01-18 16:00 UTC, ufelgen commented on pages/api/comments/[id].js
> +    }
ich schließe mich Thomas an

2023-01-18 16:00 UTC, ufelgen commented on pages/sectors/[areaSector].js
> +  console.log(sectors, "SEKTOR");
bitte löschen :)

2023-01-19 08:22 UTC, jonatsuji commented on db/Models/Comments.js
> +  routeID: { type: String, required: true },
tatsächlich bekommen alle Kommentare zu einer Route auch die ID dieser Route zugewiesen, das passt also :)

2023-01-19 13:06 UTC, merged